# Generated by Django 4.0.6 on 2022-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fileurl', models.FileField(max_length=255, upload_to='')),
                ('publisher', models.EmailField(max_length=255)),
            ],
        ),
    ]
