# Generated by Django 4.0.6 on 2022-07-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0002_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='publisher',
        ),
    ]
