# Generated by Django 4.0.6 on 2022-07-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0003_remove_filemodel_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sharing.abstractuser'),
        ),
    ]
