# Generated by Django 4.0.6 on 2022-07-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0004_filemodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sharing.filemodel')),
                ('rname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sharing.abstractuser')),
            ],
        ),
    ]
