# Generated by Django 4.0.6 on 2022-07-20 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sharing', '0007_abstractuser_mainuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='rname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
