# Generated by Django 4.0.6 on 2022-07-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0008_alter_permissionmodel_rname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionmodel',
            old_name='Filename',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='permissionmodel',
            old_name='rname',
            new_name='ruser',
        ),
    ]
