# Generated by Django 4.0.6 on 2022-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sharing', '0009_rename_filename_permissionmodel_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='suser',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
